"""job sites and discovered postings

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 09:46:40.026209
"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('search_urls', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('exclude_keywords', sa.JSON(), nullable=False),
    sa.Column('mode', sa.Enum('search_only', 'search_and_apply', name='site_mode', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('check_every_minutes', sa.Integer(), nullable=False),
    sa.Column('apply_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('max_new_per_check', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], name=op.f('fk_job_sites_portal_id_portals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sites'))
    )
    op.create_table('discovered_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_site_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('matched_category', sa.String(length=200), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_discovered_postings_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_site_id'], ['job_sites.id'], name=op.f('fk_discovered_postings_job_site_id_job_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_postings')),
    sa.UniqueConstraint('job_site_id', 'url', name=op.f('uq_discovered_postings_job_site_id'))
    )
    with op.batch_alter_table('discovered_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_postings_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_postings_job_site_id'), ['job_site_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_site_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_job_site_id'), ['job_site_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_jobs_job_site_id_job_sites'), 'job_sites', ['job_site_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_job_site_id_job_sites'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_job_site_id'))
        batch_op.drop_column('job_site_id')

    with op.batch_alter_table('discovered_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_postings_job_site_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_postings_discovered_at'))

    op.drop_table('discovered_postings')
    op.drop_table('job_sites')
    # ### end Alembic commands ###
