"""knowledge base fields

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 16:57:49.592636
"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bullets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('github_repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('source_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sync_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repos', schema=None) as batch_op:
        batch_op.drop_column('sync_error')
        batch_op.drop_column('source_hash')
        batch_op.drop_column('archived')
        batch_op.drop_column('is_private')

    with op.batch_alter_table('bullets', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
