"""pipeline runs

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24 19:27:41.203509
"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('generate', name='run_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'done', 'failed', name='run_state', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('step', sa.String(length=60), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_pipeline_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_state'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_job_id'))

    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
