"""application review window

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-25 09:59:44.491055
"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_submit_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_applications_auto_submit_at'), ['auto_submit_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_auto_submit_at'))
        batch_op.drop_column('auto_submit_at')

    # ### end Alembic commands ###
