"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 14:32:00.299312
"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Enum('user', 'system', 'agent', name='audit_actor', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('outlook_graph', 'gmail_api', 'imap', name='email_provider', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('encrypted_oauth_tokens', app.db.types.EncryptedJSON(), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('encrypted_imap_password', app.db.types.EncryptedText(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', 'error', 'disabled', name='connection_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_accounts')),
    sa.UniqueConstraint('address', name=op.f('uq_email_accounts_address'))
    )
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vector', app.db.types.VectorType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('owner_type', 'owner_id', 'chunk_index', 'model_name', name=op.f('uq_embeddings_owner_type'))
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_model_owner', ['model_name', 'owner_type'], unique=False)

    op.create_table('github_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_repos')),
    sa.UniqueConstraint('full_name', name=op.f('uq_github_repos_full_name'))
    )
    op.create_table('llm_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('anthropic', 'openai', 'gemini', 'groq', 'openrouter', 'ollama', 'openai_compatible', 'voyage', 'local_sentence_transformers', name='llm_provider_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('encrypted_api_key', app.db.types.EncryptedText(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_providers'))
    )
    op.create_table('portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('allowed_domains', sa.JSON(), nullable=False),
    sa.Column('login_method', sa.Enum('password', 'sso', 'otp', 'manual', name='portal_login_method', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('encrypted_credentials', app.db.types.EncryptedJSON(), nullable=True),
    sa.Column('selectors_config', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portals')),
    sa.UniqueConstraint('name', name=op.f('uq_portals_name'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('encrypted_value', app.db.types.EncryptedText(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('email', 'manual', name='job_source', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('detected', 'scraped', 'resume_ready', 'awaiting_approval', 'applied', 'shortlisted', 'rejected', 'offer', 'suspicious', 'ineligible', 'failed', 'paused', name='job_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('portal_id', sa.Integer(), nullable=True),
    sa.Column('apply_mode', sa.Enum('direct_link', 'read_email_then_apply', name='apply_mode', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('portal_job_ref', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('jd_structured', sa.JSON(), nullable=True),
    sa.Column('eligibility', sa.JSON(), nullable=True),
    sa.Column('ctc', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], name=op.f('fk_jobs_portal_id_portals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_jobs_dedupe_key'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_scheduled', ['status', 'scheduled_at'], unique=False)

    op.create_table('llm_task_config',
    sa.Column('task', sa.Enum('email_classifier', 'jd_analyzer', 'resume_writer', 'ats_scorer', 'final_polish', 'portal_helper', 'repo_summarizer', 'embedding', name='llm_task', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('fallback_provider_id', sa.Integer(), nullable=True),
    sa.Column('fallback_model', sa.String(length=200), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fallback_provider_id'], ['llm_providers.id'], name=op.f('fk_llm_task_config_fallback_provider_id_llm_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], name=op.f('fk_llm_task_config_provider_id_llm_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('task', name=op.f('pk_llm_task_config'))
    )
    op.create_table('sender_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('sender_match', sa.String(length=320), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=True),
    sa.Column('apply_mode', sa.Enum('direct_link', 'read_email_then_apply', name='apply_mode', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('match_forwarded', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], name=op.f('fk_sender_rules_email_account_id_email_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], name=op.f('fk_sender_rules_portal_id_portals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sender_rules'))
    )
    with op.batch_alter_table('sender_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sender_rules_email_account_id'), ['email_account_id'], unique=False)

    op.create_table('job_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('jd_attachment', 'email_attachment', 'screenshot', 'confirmation_screenshot', name='job_file_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_files_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_files'))
    )
    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_files_job_id'), ['job_id'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.Enum('email_classifier', 'jd_analyzer', 'resume_writer', 'ats_scorer', 'final_polish', 'portal_helper', 'repo_summarizer', 'embedding', name='llm_task', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider_kind', sa.Enum('anthropic', 'openai', 'gemini', 'groq', 'openrouter', 'ollama', 'openai_compatible', 'voyage', 'local_sentence_transformers', name='llm_provider_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_llm_usage_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_job_id'), ['job_id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('base_template', 'past', 'generated', 'manual_edit', name='resume_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('lineage_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tex_source', sa.Text(), nullable=False),
    sa.Column('tex_path', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('page_limit', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('score_report', sa.JSON(), nullable=True),
    sa.Column('models_used', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_resumes_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['resumes.id'], name=op.f('fk_resumes_parent_id_resumes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes')),
    sa.UniqueConstraint('lineage_id', 'version', name=op.f('uq_resumes_lineage_id'))
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_lineage_id'), ['lineage_id'], unique=False)

    op.create_table('source_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('internet_message_id', sa.String(length=998), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('original_sender', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('classification', sa.Enum('unclassified', 'job_notice', 'deadline_extension', 'reminder', 'result', 'general_notice', 'suspicious', name='email_classification', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('extracted_link', sa.Text(), nullable=True),
    sa.Column('resolved_link', sa.Text(), nullable=True),
    sa.Column('link_safe', sa.Boolean(), nullable=True),
    sa.Column('link_check_reason', sa.Text(), nullable=True),
    sa.Column('sender_rule_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], name=op.f('fk_source_emails_account_id_email_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_source_emails_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_rule_id'], ['sender_rules.id'], name=op.f('fk_source_emails_sender_rule_id_sender_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_emails')),
    sa.UniqueConstraint('account_id', 'message_id', name=op.f('uq_source_emails_account_id'))
    )
    with op.batch_alter_table('source_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_emails_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_emails_internet_message_id'), ['internet_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_emails_job_id'), ['job_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('prepared', 'approved', 'submitted', 'failed', name='application_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_file_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['confirmation_file_id'], ['job_files.id'], name=op.f('fk_applications_confirmation_file_id_job_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_applications_resume_id_resumes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)

    op.create_table('bullets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.Enum('past_resume', 'github', 'profile', name='bullet_source', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('source_resume_id', sa.Integer(), nullable=True),
    sa.Column('github_repo_id', sa.Integer(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['github_repo_id'], ['github_repos.id'], name=op.f('fk_bullets_github_repo_id_github_repos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], name=op.f('fk_bullets_source_resume_id_resumes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bullets')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_bullets_content_hash'))
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('shortlisted', 'rejected', 'offer', 'no_response', name='outcome_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_outcomes_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_application_id'), ['application_id'], unique=False)

    op.create_table('resume_bullets',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('bullet_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bullet_id'], ['bullets.id'], name=op.f('fk_resume_bullets_bullet_id_bullets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_bullets_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resume_id', 'bullet_id', name=op.f('pk_resume_bullets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_bullets')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_application_id'))

    op.drop_table('outcomes')
    op.drop_table('bullets')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('source_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_emails_job_id'))
        batch_op.drop_index(batch_op.f('ix_source_emails_internet_message_id'))
        batch_op.drop_index(batch_op.f('ix_source_emails_account_id'))

    op.drop_table('source_emails')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_lineage_id'))
        batch_op.drop_index(batch_op.f('ix_resumes_job_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_job_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_created_at'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_files_job_id'))

    op.drop_table('job_files')
    with op.batch_alter_table('sender_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sender_rules_email_account_id'))

    op.drop_table('sender_rules')
    op.drop_table('llm_task_config')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_scheduled_at'))

    op.drop_table('jobs')
    op.drop_table('settings')
    op.drop_table('portals')
    op.drop_table('llm_providers')
    op.drop_table('github_repos')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_embeddings_model_owner')

    op.drop_table('embeddings')
    op.drop_table('email_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
