"""llm gateway: notifications, usage fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 15:25:04.278953
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('info', 'warning', 'error', name='notification_level', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_notifications_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prompt_ref', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('error_kind', sa.String(length=40), nullable=True))
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_llm_usage_provider_id_llm_providers'), 'llm_providers', ['provider_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_llm_usage_provider_id_llm_providers'), type_='foreignkey')
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.drop_column('error_kind')
        batch_op.drop_column('prompt_ref')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
