"""pipeline run retries

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 19:43:54.265784
"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('not_before', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('retries', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_pipeline_runs_not_before'), ['not_before'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_not_before'))
        batch_op.drop_column('retries')
        batch_op.drop_column('not_before')

    # ### end Alembic commands ###
