"""The fact pack: everything the resume writer is allowed to use (hard rule 1), and the
guard that removes generated content not supported by it.

Sources: retrieved bullets and GitHub repo summaries, the base template's own region
content (the user's current resume), the profile, and the AutoApply signature project.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from sqlalchemy.orm import Session

from app.generation.jd import JDAnalysis
from app.knowledge.bank import BULLET
from app.knowledge.latex_text import to_text
from app.knowledge.past_resumes import build_tagger
from app.knowledge.retrieval import search
from app.knowledge.skills import SkillTagger
from app.latex.fit import find_bullets
from app.latex.sanitize import strip_comments
from app.llm.gateway import LLMGateway
from app.services.settings_service import display_name, get_app_settings, get_profile

SIGNATURE_NAME = "AutoApply Agent"
SIGNATURE_TECH = "Python, FastAPI, LangGraph, LiteLLM, PostgreSQL, pgvector, LaTeX, Next.js"


def signature_fact(author: str) -> str:
    return (
        f"{SIGNATURE_NAME} (personal project, built by {author}; tech: {SIGNATURE_TECH}): "
        "an LLM agent that tailors a LaTeX resume to each job description using only "
        "verified GitHub and past-resume data and applies through job portals with human "
        "approval. This resume was generated by it. (On the resume: ONE short bullet.)"
    )


@dataclass
class Fact:
    id: str  # "b12" bullet, "r3" repo, "base:NAME" template region, "profile", "signature"
    text: str
    source: str
    skills: list[str] = field(default_factory=list)


@dataclass
class FactPack:
    facts: list[Fact]
    author: str
    tagger: SkillTagger

    @property
    def text(self) -> str:
        return "\n".join(f.text for f in self.facts)

    def as_prompt_lines(self) -> str:
        return "\n".join(f"[{f.id}] ({f.source}) {f.text}" for f in self.facts)

    def skills(self) -> set[str]:
        return {s.lower() for s in self.tagger.tags(self.text)}


def jd_query(a: JDAnalysis, jd_text: str) -> str:
    parts = [
        a.role or "",
        a.role_category or "",
        ", ".join(a.required_skills),
        ", ".join(a.preferred_skills),
        ", ".join(a.keywords),
        " ".join(a.responsibilities),
    ]
    q = " ".join(p for p in parts if p).strip()
    return q if len(q) > 40 else jd_text[:4000]


def build_facts(
    db: Session,
    gateway: LLMGateway,
    analysis: JDAnalysis,
    jd_text: str,
    base_regions: dict[str, str],
    *,
    k: int = 40,
) -> FactPack:
    tagger = build_tagger(db)
    profile = get_profile(db)
    author = display_name(db)  # profile name, else your resume file name setting
    facts: list[Fact] = []

    keywords = [*analysis.required_skills, *analysis.preferred_skills]
    for h in search(
        db, gateway, jd_query(analysis, jd_text), k=k, keywords=keywords, tagger=tagger
    ):
        if h.owner_type == BULLET and h.bullet is not None:
            b = h.bullet
            where = " — ".join(x for x in (b.section, b.heading) if x) or b.source_type.value
            facts.append(Fact(id=f"b{b.id}", text=b.text, source=where, skills=b.skills))
        elif h.repo is not None:
            r, s = h.repo, h.repo.summary or {}
            text = "; ".join(
                x
                for x in [
                    f"Project {r.full_name.split('/')[-1]}",
                    s.get("problem") or r.description or "",
                    "tech: " + ", ".join(s.get("tech_stack") or list(r.languages)),
                    f"role: {s['role']}" if s.get("role") else "",
                    "outcomes: " + "; ".join(s["outcomes"]) if s.get("outcomes") else "",
                    "highlights: " + " | ".join(s["bullets"]) if s.get("bullets") else "",
                    f"{r.stars} GitHub stars" if r.stars else "",
                ]
                if x
            )
            facts.append(Fact(id=f"r{r.id}", text=text, source="GitHub", skills=[]))

    for name, content in base_regions.items():
        plain = to_text(content)
        if plain:
            facts.append(Fact(id=f"base:{name}", text=plain, source="current resume"))

    edu = "; ".join(
        ", ".join(
            str(x)
            for x in (
                e.degree,
                e.branch,
                e.institution,
                f"CGPA {e.cgpa}" if e.cgpa is not None else None,
                e.graduation_year,
            )
            if x
        )
        for e in profile.education
    )
    prof = "; ".join(
        x
        for x in [
            f"Education: {edu}" if edu else "",
            "Skills: " + ", ".join(profile.skills) if profile.skills else "",
            f"Location: {profile.location}" if profile.location else "",
        ]
        if x
    )
    if prof:
        facts.append(Fact(id="profile", text=prof, source="profile"))
    if get_app_settings(db).include_signature_project:
        facts.append(Fact(id="signature", text=signature_fact(author), source="this system"))
    return FactPack(facts=facts, author=author, tagger=tagger)


_NUMBER_RE = re.compile(r"\d+(?:[.,]\d+)?")


def numbers(text: str) -> set[str]:
    return {n.replace(",", "") for n in _NUMBER_RE.findall(text)}


@dataclass
class GuardResult:
    regions: dict[str, str]
    removed: list[str]  # human-readable descriptions of removed/reverted content
    signature_present: bool


def guard_regions(
    regions: dict[str, str],
    base_regions: dict[str, str],
    pack: FactPack,
    bullet_command: str,
) -> GuardResult:
    """Drop generated bullets whose numbers or skills aren't in the fact pack; revert a
    region to the base template if a non-bullet line (heading, dates, skills list) makes
    an unsupported claim."""
    facts_text = pack.text
    fact_numbers = numbers(facts_text)
    fact_skills = pack.skills()
    removed: list[str] = []
    out: dict[str, str] = {}

    for name, content in regions.items():
        bullet_lines = {b.line_index for b in find_bullets(name, content, bullet_command)}
        kept: list[str] = []
        revert = False
        for idx, line in enumerate(content.splitlines()):
            plain = to_text(strip_comments(line))
            if not plain:
                kept.append(line)
                continue
            bad_numbers = numbers(plain) - fact_numbers
            bad_skills = {s.lower() for s in pack.tagger.tags(plain)} - fact_skills
            if not bad_numbers and not bad_skills:
                kept.append(line)
                continue
            why = ", ".join(
                [f"number {n}" for n in sorted(bad_numbers)]
                + [f"skill {s}" for s in sorted(bad_skills)]
            )
            if idx in bullet_lines:
                removed.append(f"{name}: removed bullet with unsupported {why}: {plain[:160]}")
            else:
                revert = True
                removed.append(f"{name}: reverted to your current content (unsupported {why})")
                break
        out[name] = base_regions.get(name, "") if revert else "\n".join(kept)

    if not any(f.id == "signature" for f in pack.facts):
        # not your project (setting off): an AutoApply entry the model wrote anyway goes
        for name, content in out.items():
            cleaned = drop_entry(content, SIGNATURE_NAME)
            if cleaned != content:
                out[name] = cleaned
                removed.append(f"{name}: removed the {SIGNATURE_NAME} entry (not your project)")
    out = {name: drop_empty_lists(content, bullet_command) for name, content in out.items()}
    signature = any(SIGNATURE_NAME.lower() in to_text(c).lower() for c in out.values())
    return GuardResult(regions=out, removed=removed, signature_present=signature)


def drop_empty_lists(content: str, bullet_command: str) -> str:
    """Remove itemize/enumerate blocks left without a single bullet (LaTeX rejects them)."""
    lines = content.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        if re.match(r"\s*\\begin\{(itemize|enumerate)\}", lines[i]):
            j = i + 1
            while j < len(lines) and not re.match(r"\s*\\end\{(itemize|enumerate)\}", lines[j]):
                j += 1
            block = lines[i + 1 : j]
            if not any(re.search(rf"\\{re.escape(bullet_command)}\b", x) for x in block):
                i = j + 1  # skip the empty list entirely
                continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def drop_entry(content: str, name: str) -> str:
    """Remove a whole entry (its heading line, the next few lines and its bullet list)."""
    lines = content.splitlines()
    for i, line in enumerate(lines):
        if name.lower() in to_text(strip_comments(line)).lower():
            end = i
            for j in range(i, min(len(lines), i + 8)):
                if re.match(r"\s*\\end\{(itemize|enumerate)\}", lines[j]):
                    end = j
                    break
            return "\n".join(lines[:i] + lines[end + 1 :])
    return content
